# Write a program to input eight numbers from the user and display all the unique numbers (once) 
# Remember Unique means the use of set
s=set()
n = input("Enter the number1:")
s.add(int(n))
n = input("Enter the number2:")
s.add(int(n))
n = input("Enter the number3:")
s.add(int(n))
n = input("Enter the number4:")
s.add(int(n))
n = input("Enter the number5:")
s.add(int(n))
n = input("Enter the number6:")
s.add(int(n))
n = input("Enter the number7:")
s.add(int(n))
n = input("Enter the number8:")
s.add(int(n))
print(s)
